include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: sweep_central_dongle dongle_display
